version: '3.3'
services:
  api:
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
